# Generated by slice2py - DO NOT EDIT!
#

import Ice
Ice.updateModule("Smarthome")

# Modules:
import smarthome_ice

# Submodules:
from . import AirConditioning
from . import Heating
from . import Kitchen
from . import Lighting
from . import Controller
