/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks.getByName<JavaExec>("run") {
  println("setting up run task")
  standardInput = System.`in`
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13.2")

    implementation("com.rabbitmq:amqp-client:5.14.2")
    implementation("org.apache.logging.log4j:log4j-core:2.17.2")
//    implementation("org.slf4j:slf4j-log4j1:1.7.29")
    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("org.kkafara.App")
}
